version: '3'

services:

  api:
    container_name: phonebook-api
    # Tekuci radni direktorijum gde se nalazi Dockerfile
    build: .
    image: phonebook:latest
    volumes:
      - ./:/app
    depends_on:
      - postgres
    ports:
      - 5000:5000
    command: >
      python -m server.main

  # https://hub.docker.com
  postgres:
    container_name: phonebook-postgres
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    #volumes:
    #  - ./../cities.db:/cities.db
    ports:
      - 5432:5432
    command:
      postgres
      -c logging_collector=on
      -c log_destination=stderr
      -c log_directory=/var/lib/postgresql/data
      -c log_statement='all'